GET http://localhost:3000/





// user module requests 
GET http://localhost:3000/users/222
GET http://localhost:3000/users/1/?limit=20&offset=10



POST http://localhost:3000/users
Content-Type: application/json

{
   "firstName": "waqas",
   "lastName": "ali",
   "email": "waqas@gmail.com",
   "password": "1234569999" 
}

POST http://localhost:3000/posts
Content-Type: application/json


{
  "title": "My First Post",
  "postType": "page",
  "slug": "my-first-postddd",
  "status": "review",
  "content": "This is the content of my first post.",
  "schema": "{\"type\":\"text\",\"content\":\"This is a sample schema\"}",
  "featureImageUrl": "https://example.com/image.jpg",
  "publishOn": "2024-11-20T12:00:00Z",
  "tags": "tech"
 
}

