GET http://localhost:3001/





// user module requests 
GET http://localhost:3001/users/
GET http://localhost:3001/users/22




POST http://localhost:3001/users
Content-Type: application/json

{
   "firstName": "waqas",
   "lastName": "ali",
   "email": "waqddas@362186318138713sail.com",
   "password": "1234569999" 
}

POST http://localhost:3001/posts
Content-Type: application/json


{
  "title": "My First Post",
  "postType": "page",
  "slug": "my-first-postddddddd",
  "status": "review",
  "content": "This is the content of my first post.",
  "schema": "{\"type\":\"text\",\"content\":\"This is a sample schema\"}",
  "featureImageUrl": "https://example.com/image.jpg",
  "publishOn": "2024-11-20T12:00:00Z",
  "tags": "tech",
  
  "authorId":1

}

