GET http://localhost:3000/





// user module requests 
GET http://localhost:3000/users/
GET http://localhost:3000/users/22





POST http://localhost:3001/posts
Content-Type: application/json


{
  "title": "My First Post",
  "postType": "page",
  "slug": "my-first-postddddddd",
  "status": "review",
  "content": "This is the content of my first post.",
  "schema": "{\"type\":\"text\",\"content\":\"This is a sample schema\"}",
  "featureImageUrl": "https://example.com/image.jpg",
  "publishOn": "2024-11-20T12:00:00Z",
  "tags": "tech",
  
  "authorId":1

}

POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
  "firstName":"waqas" ,
  "lastName":"awan",
  "email" :"waqasAdmin@gmail.com" ,
  "password" :"12345678" ,
  "role":"admin"

}




POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  
  "email" :"waqasAdmin@gmail.com",
  "password" :"12345678" 

}


GET http://localhost:3000/users

headers :"Be"